name: Fly Deploy

on: [push]

env:
    FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
    deploy:
        name: Deploy app
        runs-on: ubuntu-latest
        if: "contains(github.event.head_commit.message, '(deploy)')"
        steps:
            - uses: actions/checkout@v3
            - uses: superfly/flyctl-actions@1.1
              with:
                  args: "deploy"